server:
  host: ""
  port: "8080"

db:
  username: "postgres"
  password: "admin"
  host: "order-service-db"
  port: "5432"
  dbname: "postgres"
  ssl_mode: "disable"

kafka:
  brokers:
    - "kafka:9092"
  topic: "orders"
  group_id: "order-group"

CSRF:
  Secret: "secret_key"